/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CalculatorTest {

     @Test void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
     }
}
